name: Build 1Panel-Global Docker Image

on:
  schedule:
    - cron: "0 14 * * 2"
    - cron: "0 11 * * 5"
  
  workflow_dispatch:
    inputs:
      version:
        description: "æŒ‡å®šç‰ˆæœ¬å· (ç•™ç©ºåˆ™è‡ªåŠ¨èŽ·å–æœ€æ–°ç‰ˆ)"
        required: false
        type: string


jobs:
  build_images:
    name: Build V1 Global
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version
        id: get_version
        run: |
          VER_INPUT=${{ inputs.version }}
          if [ -n "$VER_INPUT" ]; then
            echo "PANELVER=${VER_INPUT}" >> $GITHUB_OUTPUT
            echo "ðŸ‘‰ Using manual version: ${VER_INPUT}"
          else
            VER_LATEST=$(curl -fsSL https://resource.1panel.pro/stable/latest)
            echo "PANELVER=${VER_LATEST}" >> $GITHUB_OUTPUT
            echo "ðŸ”Ž Detected latest version: ${VER_LATEST}"
          fi

      - name: Build and push V1 Global
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./V1
          file: ./V1/Dockerfile-Global
          build-args: |
            PANELVER=${{ steps.get_version.outputs.PANELVER }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/1panel:global-${{ steps.get_version.outputs.PANELVER }},${{ secrets.DOCKERHUB_USERNAME }}/1panel:global-v1

